name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Ou 'main' dependendo da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Ajuste para a versão 20, igual à sua versão local

    - name: Install dependencies
      run: npm install

    - name: Build project
      env:
        URL: ${{ secrets.URL }}
        KEY: ${{ secrets.KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web-build
